version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_SERVER: host.docker.internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql